# Default OpenNMT parameters from the Lua version.
train:
  batch_size: 64
  batch_type: tokens
  bucket_width: 1
  save_checkpoints_steps: 5000
  save_summary_steps: 50
  train_steps: 1000000
  maximum_features_length: 50
  maximum_labels_length: 50

  # Consider setting this to -1 to match the number of training examples.
  sample_buffer_size: 1000000

eval:
  eval_delay: 18000  # Every 5 hours.

infer:
  batch_size: 30
