embeddings {
  tensor_name: "transformer/encoder/inputter_0/w_embs:0"
  metadata_path: "transformer_encoder_inputter_0_w_embs.txt"
}
embeddings {
  tensor_name: "transformer/encoder/inputter_1/w_embs:0"
  metadata_path: "transformer_encoder_inputter_1_w_embs.txt"
}
embeddings {
  tensor_name: "transformer/encoder/inputter_2/w_embs:0"
  metadata_path: "transformer_encoder_inputter_2_w_embs.txt"
}
embeddings {
  tensor_name: "transformer/encoder/inputter_3/w_embs:0"
  metadata_path: "transformer_encoder_inputter_3_w_embs.txt"
}
embeddings {
  tensor_name: "transformer/decoder/w_embs:0"
  metadata_path: "transformer_decoder_w_embs.txt"
}
